language: java
jdk:
- oraclejdk11
deploy:
  api_key:
    secure: NrOMibZ+Rw/NbZ4s74tvodwMXMWbfkEdvfT67BERCM9lZ3pKeAJvg+40mkJ/EhzwhyHpEXFbemXGMk3c0vYKXDauCerT5ofj38HDRaRAKLor4sseKLoarTJwtKoATC+X6gF76xy2VkPpUhGlfa3GyemPe7tufkWX9bpji5mZWLAz9pbZvPt9BiIHrAdFkshgI4P2JAbeucrqic5Us7hL74uotBfj67V0sTzETgYTB/XPffXSkkdNiEz9jecxAEDe8ZIFKnrsOKD2+ONdNRv63f0CLDgJAMJmRisTSI8vHXIW2bpJsLno6f0DLGKB/rIr76E1sJYTwtqFhDkVgM0vraDuk87qAITsOxm5RmmwZpXgT3Mz1bo59sMpQJk6Bvi63t5VdzEdD+hbO8QFW6dRj+YL5oZTZQw+G59Wubze34GtnHmEU29OGRerHQZ18kKwmNgq3kkZNqpcQevUXqyPynaXrEgx257ayId8cfmKSQ1Xvqto0IeUcRqlcQncmcSqKgXskmyW2gBu0BuE6t1LvcIToq5NhaK6dg8P8vbtBP0O2MugmniDbo5BGw3yYDxdQ8skgef8TIgiGBJSQaHlN9VD4oaxmQjFDctzQWc/ANVJYIjqMuyUuNHjLcdmaP7j1xjvZrCeMcbN+65N7Kmn7OqMNsELKprm7fw/Jnx/JFE=
