language: java
jdk:
- oraclejdk11
env:
  global:
    secure: hLpW3FzUBxALr0H4VNhL3rAbrvV3rdG5vU3RI9DgiuvxM1KS988vs5r9QB161p1wn4eaqdHR8GxpalX3TQXVTIwoMmvvSaJtko9S5sLATkbvWxx3wW6mI3J3LuJoM2jqBQ8ZuprXB0heHxAp5Cisb2pYnqcHM+e3hjX8ZU4/aCUUi8AcX9hG+305dqv++tmKq4uAgbvc4+2+tt3s52cRr8ISPwSGxZAuEN5U88vqBaTA0+VcMj6FfK9zIsytkFLUTMoLwPUWhhzqFQoPrpGPbg8EIeYQpI1YzaS/uoJQBd31b6L0Hfo6QoLxg4TSfCIOnYJO2KLgEXZHp+I2XmNGgVPJ6PF0HjnVD7bxJiW5rnQRLUFgDYblMusTbuwL/QfzMw1jXEDzR/s/rJu2lVL1S1QiqRdKn1CrlP+9eF435VgaqEDnp8hHwdwcZy/PSzLdVp1t0hXRAXLsOsXiOOCdKAcb00SugtlucBRoQMfa0a3LTV9ifEOW7SsawrpXN91PIulTzWV3WI8XxO5d+OdEBR9HULQDSwGTRxdsvT4ep6gzTIh4eUTFxZuhjkYnt9hrjjbLlGu9w92Y+sxDjkkgns0eoC1tyZfUxRwqnGZxQqIjh++q7cSA4bDXFkPdQEZtgU4gxMogwMBQdcYozzAOE2O3BML6ykS9RAG3qckoBm8=
deploy:
  provider: heroku
  app: bootshorten
  api_key:
    secure: Ov8i25ARjCEvA+jNdz8nG5nfAQMO4DD9GxENu7W+QQ4lwlZ8BaiM7gtGAcTx9FkpMtVhDUDWhLbuABwT7ki1FOifzsW5pTvPslYelPinuD5+bfLOcOofXswddUtAXVh9gR8qzJlaElE/2fwOTMlDNtfegqh5rwpQG4RNIHPfzChr26VHNRrI2J2yVYzrezDhXgWtLN5x7fPXR7C8e+x6NfHZhrJ7RqZTj885K3agmpB/VD5m0M7RuxV3cCsf2WjJVL/2WXYWAhNhhdFLU/IxQGMABvq33vwvULCEhm2oKFfZfemtBjZFicy2vBxYstfgIJVVeQL+R9p+gwZlgriQYGhlIouLQg4f877UO4HwPdOlwytjucFmWBrxh5GgQNlsuMry9/qYhD72mQBC/9j/dCt7zAi4Aa/JDdk6N7NRRfaGoAQVkOohnSOvkXTxQX24vxKKkPeV4tRHpWYph5i/VNCk4M1+ChOQLaPtGThULmx7VrK844ryz6SGXIzAT7RfOu7ywZaZ1vdW0/t2RU6Om+uLcNdI53UbT++MLEmgoSed200WaPGB2mlIx/dMyBJelCZ2tKhOzQo6NBv1BEoifatAAWv2vgtdB6eX9ri+iH4bQcP/nqpeXGsAFUcWIHegvcpSPq58hD3wSaIUW3ecbM45LGJrq5L96cAOoV2GHXc=
script:
  ./gradle build -x test
