language: java
jdk:
- oraclejdk11
deploy:
  api_key:
    secure: A88jAyWosFbc1BhWX65JJrlbWf0Q5ucWIXFdB3N/vIwFIOcA3kZzAdl4ZWYT4IbZKmzPM/uzRmIajpmGA4jp5r4pU8lIPUMTD+Hf/DIu0P5lvaudUW4DL6lPYTCIM/qYdCxsIQDJThUMeZn76qmnlTHj7Be7lnJ+p/6HIbQzV26/HDzGHl4PjsbUbvpjt36txUPGiFPrXufWwt+bd/eBcILuBX1m63hs3yIO2b7joVheVPDc1NXrcxjHB40sFfUiiMiFWWr/w1trtB7u0fnQy15/D2JnzjbYR94TaEQhvipgMw+DfpajJmVQ4lB+m2G4a3kcOhOvX9jqlyVQ8NM0c6j46PDGbtQDcrVgZk++sSFTkq+2O/88Lf6gsRSHxe46/5jBBG5zk1FzWMeCo1E2Un/vnozLCzcBW3NpQxiJh7bAQqqJ28olHMmq33tT+oCsZmVZSmlaGr8VUlTLEgeLJdXERuPmsDJ1Lk4cKzTeM6ny7tzPE8t4vVIM/Mh5qNaqrCpAf0UU0HdqHde1J7faTg6/ziDxIexaDS3nEv+QEvmKJCha4AjJ/MLZp8XjORSOjGWdx8bt+N1JTVbleBaeoAhJI+NuJVxQoHt8rrQJhDL8AnZT3uEff+c8PUbjsvmqlPcBjKj59Vf+MAfJ1e9zme+zkUgvgrWQy0CCvZvOC0o=
