language: java
jdk:
- oraclejdk11
env:
  global:
    secure: hLpW3FzUBxALr0H4VNhL3rAbrvV3rdG5vU3RI9DgiuvxM1KS988vs5r9QB161p1wn4eaqdHR8GxpalX3TQXVTIwoMmvvSaJtko9S5sLATkbvWxx3wW6mI3J3LuJoM2jqBQ8ZuprXB0heHxAp5Cisb2pYnqcHM+e3hjX8ZU4/aCUUi8AcX9hG+305dqv++tmKq4uAgbvc4+2+tt3s52cRr8ISPwSGxZAuEN5U88vqBaTA0+VcMj6FfK9zIsytkFLUTMoLwPUWhhzqFQoPrpGPbg8EIeYQpI1YzaS/uoJQBd31b6L0Hfo6QoLxg4TSfCIOnYJO2KLgEXZHp+I2XmNGgVPJ6PF0HjnVD7bxJiW5rnQRLUFgDYblMusTbuwL/QfzMw1jXEDzR/s/rJu2lVL1S1QiqRdKn1CrlP+9eF435VgaqEDnp8hHwdwcZy/PSzLdVp1t0hXRAXLsOsXiOOCdKAcb00SugtlucBRoQMfa0a3LTV9ifEOW7SsawrpXN91PIulTzWV3WI8XxO5d+OdEBR9HULQDSwGTRxdsvT4ep6gzTIh4eUTFxZuhjkYnt9hrjjbLlGu9w92Y+sxDjkkgns0eoC1tyZfUxRwqnGZxQqIjh++q7cSA4bDXFkPdQEZtgU4gxMogwMBQdcYozzAOE2O3BML6ykS9RAG3qckoBm8=
